"""
prompts.py
──────────
Pure functions that build every prompt string used in the lab.
No Streamlit, no API calls — just string construction.
This makes each strategy trivially testable in isolation.
"""


# ── Strategy Builders ─────────────────────────────────────────────────────────

def build_zero_shot(task: str, inp: str) -> str:
    """
    Zero-Shot: bare instruction with no examples or scaffolding.
    Best for simple, well-defined tasks where the model's prior
    knowledge is sufficient.
    """
    return (
        f"Task: {task}\n"
        f"Input: {inp}\n"
        f"Answer:"
    )


def build_few_shot(task: str, inp: str, examples: list[dict]) -> str:
    """
    Few-Shot: 3 labeled input→output examples precede the live input.
    Examples are auto-generated by `api_client.generate_few_shot_examples`.
    Guides the model toward the expected output format and style.
    """
    ex_lines = "\n".join(
        f"  Input: {e['input']} → Output: {e['output']}"
        for e in examples
    )
    return (
        f"Task: {task}\n\n"
        f"Examples:\n{ex_lines}\n\n"
        f"Now answer:\n"
        f"Input: {inp}\n"
        f"Output:"
    )


def build_chain_of_thought(task: str, inp: str) -> str:
    """
    Chain-of-Thought (CoT): explicitly prompts step-by-step reasoning
    before committing to a final answer. Particularly effective for
    multi-step or ambiguous tasks.
    """
    return (
        f"Task: {task}\n"
        f"Input: {inp}\n\n"
        f"Let's think step by step before giving a final answer.\n\n"
        f"Step-by-step reasoning:\n"
        f"Final Answer:"
    )


def build_role_prompting(task: str, inp: str) -> str:
    """
    Role Prompting: assigns an expert persona before the task.
    Primes the model to respond with authority and domain precision.
    """
    return (
        f"You are an expert specializing in {task}. "
        f"You have 20 years of experience and always give precise, accurate answers.\n\n"
        f"Task: {task}\n"
        f"Input: {inp}\n"
        f"Expert Answer:"
    )


def build_bad_prompt(task: str, inp: str) -> str:
    """
    Deliberately vague / bad prompt — used in the 'Bad Prompt Demo'.
    Illustrates what happens without clear task context, format hints,
    examples, or persona.
    """
    return f"do the thing with {inp}"


# ── Dispatcher ────────────────────────────────────────────────────────────────

def build_prompt(strategy: str, task: str, inp: str, examples: list[dict] | None = None) -> str:
    """
    Dispatch to the correct builder by strategy name.
    Raises ValueError for unknown strategies.
    """
    match strategy:
        case "Zero-Shot":
            return build_zero_shot(task, inp)
        case "Few-Shot":
            return build_few_shot(task, inp, examples or [])
        case "Chain-of-Thought":
            return build_chain_of_thought(task, inp)
        case "Role Prompting":
            return build_role_prompting(task, inp)
        case _:
            raise ValueError(f"Unknown strategy: {strategy!r}")
